server:
  port: 8000
  servlet:
    context-path: /master
spring:
  application:
    name: masterdata-service
  config:
    import: configserver:http://localhost:8888
  zipkin:
    base-url: http://localhost:9411
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
management:
  endpoints:
    web:
      exposure:
        include: "*"